---
type: catalogue
serverPort: 8000
# Use dataPortStart and dataPortEnd optionally for data connection
# dataPortStart: 
# dataPortEnd:
stores: 
  - default: <machine-ln00x>.cscs.ch:7000
    serveLocalData: true
engine: toc
schema: /path/to/fdb-schema
spaces:
- handler: Default
  roots:
  - path: /path/to/fdb-root
    writable: true
    visit: true
