---
type: catalogue
serverPort: 8000
stores: [ "balfrin-ln002.cscs.ch:7000" ] # balfrin login node where store is running # used on archival
localStores: [ "balfrin-ln002.cscs.ch:7000" ] # can have multiple of these per login node for example to spread the load. # used to inject the endpoint during retrieval.
engine: toc
schema: /scratch/mch/vcherkas/fdb-setup/fdb-schema
spaces:
- handler: Default
  roots:
  - path: /scratch/mch/vcherkas/fdb-root
    writable: true
    visit: true
